### ISSUE TITLE
Change image path to absolute path

### ISSUE THREAD

**Issue by L1so** [semanticdata/mabuya#4]
**Describe the bug**
Failed to display the image due to path issues, the theme act as if there was new path named named exactly after my post, below is screenshot from obsidian (markdown editor) I use to write blog posts.

![image](https://github.com/user-attachments/assets/7712e91a-46d1-4626-ad72-e835b2c5aade)

However, the site refuses to load the image, apparently the image doesn't exist on this path: `http://127.0.0.1:1111/libgamemodeauto-so-0-from-ld-preload-cannot-be-preloaded/static/images/gargoyle.png`.
![Recording 2024-09-15 at 13 55 39](https://github.com/user-attachments/assets/5e35f836-bc04-49da-ac2c-696e4a397740)

Instead, the image was in fact located on this path: `http://127.0.0.1:1111/images/gargoyle.png`.
![image](https://github.com/user-attachments/assets/46d61f1c-11b3-4ce2-89fe-dba7f27c5d39)

*To Reproduce**

1. Create new image directory on `static` directory
2. Put image there
3. References the image with markdown style (e.g. `![Alt text](static/images/gargoyle.png)`
4. Image will load on obsidian, but doesn't load on zola site.

**Expected behavior**
Image will load on either obsidian editor and zola site. 

**Desktop (please complete the following information):**

- Device: PC
- OS: Debian 12 Bookworm
- Browser: Firefox 130.0

**Additional context**
I found one interesting thing, the image will load if I add leading slash like this `![Alt text](/images/gargoyle.png)`, but after applying this fix, obsidian no longer recognize the image and will simply say `“/images/gargoyle.png” could not be found.`.

**Comment by semanticdata** [comment]
Hey @L1so!

This behaviour is related to how Zola deals with [asset colocation](https://www.getzola.org/documentation/content/overview/#asset-colocation). When you run Zola, it builds your site under the `public` directory, copying the contents of the `static` folder directly into `public`. Here's a snippet from the documentation:

> Any files/directories that you place in the static directory will be copied, without modification, to the public directory.

This means that in your current configuration, your site structure looks something like this after processing:

```
public/
├── assets/
│   └── ...
├── fonts/
│   └── ...
├── images/
│   └── gargoyle.png
└── main.css
```

As you can see, Zola does not have a static directory afterwards. This conflicts with how Obsidian links to assets in its vault. Using `static` is *generally* intended for globally available assets like favicons.

My recommendation would be to co-locate your images within the `content` directory. Something like this:

```md
content/
├── 2024-09-14-libgamemodeauto.so.0-from-ld_preload-cannot-be-preloaded/
│   ├── gargoyle.png
│   └── index.md
├── 2023-06-06-markdown-showcase/
│   └── index.md
├── 2024-08-12-experience-with-ssg/
│   └── index.md
├── 2024-08-16-twgok-revisited-(in-form-of-manga)/
│   └── index.md
├── 2024-09-08-public-cuda-gpg-key-does-not-appear-to-be-installed/
│   └── index.md
└── _index.md
```

You'll then be able to link images and have them work both on Obsidian and Zola. Like this:

```md
![Alt text](gargoyle.png)
```

I've tested it on my side and it seems to work. I hope this works and is an acceptable solution for you.

**Comment by L1so** [comment]
Thanks, I tried to figure this out for last 3 days and you just did it for 15 minutes, I really appreciate it !

**Comment by L1so** [comment]
Not related to this issue but can you give me clue on how to do this?

1. Have copy to clipboard button on code highlight
2. Have line number on the code highlight
Thanks !

**Comment by semanticdata** [comment]
## 1. Copy to Clipboard Button

I don't think there is an easy way to do this. Might need to use a JS library like [clipboard.js](https://clipboardjs.com/).

## 2. Line Numbers on Code Blocks

You can activate line numbers by following [Syntax Highlighting - Annotations](https://www.getzola.org/documentation/content/syntax-highlighting/#annotations) from Zola's documentation.

In short, by adding `lineos` after a comma in your markdown, you can activate the line numbers in Zola like so:

```
```rust
use highlighter::highlight;
let code = "...";
highlight(code);
```

```
```rust,linenos
use highlighter::highlight;
let code = "...";
highlight(code);
```

This does create a new structure within codeblocks, so you'll need to apply new styles. Here's a quick one I put together from the example provided in the [documentation](https://www.getzola.org/documentation/content/syntax-highlighting/#styling-codeblocks). Maybe it can help you get started.

```css
pre {
    padding: 1rem;
    overflow: auto;
}
/* The line numbers already provide some kind of left/right padding */
pre[data-linenos] {
    padding: 1rem 0;
    padding: 0;
}
pre table td {
    padding: 0 0.25rem;
    color: white;
    // border: 0;
}
/* The line number cells */
pre table td:nth-of-type(1) {
    text-align: center;
    user-select: none;
}
pre mark {
    /* If you want your highlights to take the full width */
    display: block;
    /* The default background colour of a mark is bright yellow */
    background-color: rgba(254, 252, 232, 0.9);
}
pre table {
    width: 100%;
    border-collapse: collapse;
    border: 0;
}

pre code {
    border: 0;
}
```

You should be able to just drop it in the `sass/_custom.css`. Here's how it looks on my quick test:

![image](https://github.com/user-attachments/assets/180745ac-5ec7-43b4-a4a5-c186f51f8817)

---

I'll go ahead and close this issue since we addressed the images location issue. If you have more questions feel free to open a new issue for it.

Thanks!
